"use client"

import { useState, useEffect } from "react"
import { Lightbulb, CheckCircle2, AlertTriangle, TrendingUp, X, Download, Loader2 } from "lucide-react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { useTraffixContext } from "@/lib/traffix-context"
import { fetchRecommendations, type Recommendation } from "@/lib/api-client"

export function AnalystRecommendations() {
  const { region, timePeriod, customDateRange, refreshTrigger } = useTraffixContext()
  const [recommendations, setRecommendations] = useState<Recommendation[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [selectedRec, setSelectedRec] = useState<Recommendation | null>(null)
  const [showDialog, setShowDialog] = useState(false)
  
  useEffect(() => {
    async function loadRecommendations() {
      try {
        setLoading(true)
        setError(null)
        
        const data = await fetchRecommendations(
          region,
          timePeriod,
          timePeriod === 'CUSTOM' ? customDateRange.start : undefined,
          timePeriod === 'CUSTOM' ? customDateRange.end : undefined
        )
        
        setRecommendations(data)
      } catch (err) {
        console.error('Error loading recommendations:', err)
        setError('Failed to load recommendations')
      } finally {
        setLoading(false)
      }
    }

    loadRecommendations()
  }, [region, timePeriod, customDateRange, refreshTrigger])
  
  const handleViewFullAnalysis = (rec: Recommendation) => {
    setSelectedRec(rec)
    setShowDialog(true)
  }
  
  const handleExportReport = (rec: Recommendation) => {
    // Generate a text report
    const report = `
TRAFFIX REMEDIATION PLAN
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Generated: ${new Date().toLocaleString()}
Region: ${region}
Category: ${rec.category}
Confidence: ${rec.confidence}

PROBLEM STATEMENT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Location: ${rec.location}

${rec.insight}

FULL ANALYSIS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${rec.full_analysis}

RECOMMENDED ACTIONS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${rec.actions.map((action, i) => `${i + 1}. ${action}`).join('\n')}

EXPECTED IMPACT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${rec.impact}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
This report was generated by TRAFFIX AI-Powered Transportation Analytics
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
`
    
    // Create and download file
    const blob = new Blob([report], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `traffix-remediation-${rec.id}-${new Date().toISOString().split('T')[0]}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  return (
    <>
      <div className="rounded-xl border bg-card shadow-sm">
        <div className="border-b bg-muted/30 px-6 py-4">
          <div className="flex items-center gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary">
              <Lightbulb className="h-5 w-5 text-primary-foreground" />
            </div>
            <div>
              <h2 className="text-lg font-semibold text-foreground">Analyst Recommendations</h2>
              <p className="text-sm text-muted-foreground">AI-generated decision support based on real data</p>
            </div>
          </div>
        </div>

        <div className="p-6 space-y-4">
          {loading ? (
            <div className="flex items-center justify-center py-12">
              <Loader2 className="h-8 w-8 animate-spin text-primary" />
              <span className="ml-3 text-muted-foreground">Analyzing traffic patterns...</span>
            </div>
          ) : error ? (
            <div className="text-center py-12 text-muted-foreground">
              {error}
            </div>
          ) : recommendations.length === 0 ? (
            <div className="text-center py-12 text-muted-foreground">
              No recommendations available for the selected period.
            </div>
          ) : (
            recommendations.map((rec) => (
              <div key={rec.id} className="rounded-lg border bg-background p-4">
                <div className="flex items-start justify-between mb-3">
                  <div className="flex-1">
                    <div className="flex items-center gap-2 mb-2">
                      <Badge variant="outline" className="text-xs">
                        {rec.category}
                      </Badge>
                      <span className="text-xs text-muted-foreground">📍 {rec.location}</span>
                    </div>
                    <p className="text-sm text-foreground mb-2">{rec.insight}</p>
                    <Badge variant={rec.confidence === "High" ? "default" : "secondary"} className="gap-1.5">
                      <CheckCircle2 className="h-3 w-3" />
                      {rec.confidence} Confidence
                    </Badge>
                  </div>
                </div>

                <div className="space-y-3 mb-3">
                  <div>
                    <p className="text-xs font-semibold text-foreground mb-2 flex items-center gap-2">
                      <AlertTriangle className="h-3 w-3" />
                      Suggested Actions:
                    </p>
                    <ul className="space-y-1">
                      {rec.actions.map((action, j) => (
                        <li key={j} className="text-xs text-muted-foreground pl-4">
                          • {action}
                        </li>
                      ))}
                    </ul>
                  </div>

                  <div className="flex items-center gap-2 text-xs">
                    <TrendingUp className="h-3 w-3 text-primary" />
                    <span className="text-muted-foreground">Expected Impact:</span>
                    <span className="font-medium text-foreground">{rec.impact}</span>
                  </div>
                </div>

                <div className="flex gap-2">
                  <Button 
                    variant="outline" 
                    size="sm" 
                    className="text-xs bg-transparent"
                    onClick={() => handleViewFullAnalysis(rec)}
                  >
                    View Full Analysis
                  </Button>
                  <Button 
                    variant="ghost" 
                    size="sm" 
                    className="text-xs gap-1.5"
                    onClick={() => handleExportReport(rec)}
                  >
                    <Download className="h-3 w-3" />
                    Export Report
                  </Button>
                </div>
              </div>
            ))
          )}
        </div>
      </div>

      {/* Full Analysis Dialog */}
      {showDialog && selectedRec && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4" onClick={() => setShowDialog(false)}>
          <div className="bg-card border rounded-xl shadow-lg max-w-3xl w-full p-6" onClick={(e) => e.stopPropagation()}>
            <div className="flex items-start justify-between mb-4">
              <div>
                <h3 className="text-xl font-semibold text-foreground">Full Remediation Plan</h3>
                <p className="text-sm text-muted-foreground mt-1">{selectedRec.location} • {selectedRec.category}</p>
              </div>
              <Button 
                variant="ghost" 
                size="sm" 
                onClick={() => setShowDialog(false)}
                className="h-8 w-8 p-0"
              >
                <X className="h-4 w-4" />
              </Button>
            </div>

            <div className="space-y-4">
              {/* Problem Statement */}
              <div>
                <h4 className="text-sm font-semibold text-foreground mb-2">Problem Statement</h4>
                <div className="bg-muted/30 rounded-lg p-4">
                  <p className="text-sm text-foreground">{selectedRec.insight}</p>
                </div>
              </div>

              {/* Full Analysis */}
              <div>
                <h4 className="text-sm font-semibold text-foreground mb-2">Full Analysis & Remediation Plan</h4>
                <div className="bg-blue-50 dark:bg-blue-950/20 rounded-lg p-4 border border-blue-200 dark:border-blue-900">
                  <p className="text-sm text-foreground leading-relaxed">{selectedRec.full_analysis}</p>
                </div>
              </div>

              {/* Recommended Actions */}
              <div>
                <h4 className="text-sm font-semibold text-foreground mb-2 flex items-center gap-2">
                  <AlertTriangle className="h-4 w-4" />
                  Recommended Actions
                </h4>
                <div className="bg-background rounded-lg border p-4">
                  <ol className="space-y-2">
                    {selectedRec.actions.map((action, i) => (
                      <li key={i} className="text-sm text-foreground flex gap-2">
                        <span className="font-semibold min-w-[1.5rem]">{i + 1}.</span>
                        <span>{action}</span>
                      </li>
                    ))}
                  </ol>
                </div>
              </div>

              {/* Expected Impact */}
              <div>
                <h4 className="text-sm font-semibold text-foreground mb-2 flex items-center gap-2">
                  <TrendingUp className="h-4 w-4 text-primary" />
                  Expected Impact
                </h4>
                <div className="bg-green-50 dark:bg-green-950/20 rounded-lg p-4 border border-green-200 dark:border-green-900">
                  <p className="text-sm text-foreground font-medium">{selectedRec.impact}</p>
                </div>
              </div>

              {/* Confidence Badge */}
              <div className="flex items-center justify-between pt-4 border-t">
                <Badge variant={selectedRec.confidence === "High" ? "default" : "secondary"} className="gap-1.5">
                  <CheckCircle2 className="h-3 w-3" />
                  {selectedRec.confidence} Confidence Analysis
                </Badge>
                <Button 
                  size="sm" 
                  className="gap-1.5"
                  onClick={() => handleExportReport(selectedRec)}
                >
                  <Download className="h-3 w-3" />
                  Download Full Report
                </Button>
              </div>
            </div>
          </div>
        </div>
      )}
    </>
  )
}
